apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: https://github.com/sunishsurendrank/argocd.git 
    targetRevision: HEAD
    path: demoapp
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp
