apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sunishsurendrank/argocd.git
    targetRevision: HEAD
    path: demoapp
  destination:
    server: https://kubernetes.default.svc
    namespace: default
